const express = require('express');
const cors = require('cors');
const connectDB = require('./config/db');
require('dotenv').config();
const app = express();
connectDB();
app.use(cors());
app.use(express.json());
app.use('/api/helados', require('./routes/heladoRoutes'));
app.use('/api/empleados', require('./routes/empleadoRoutes'));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
app.use('/api/dolar', require('./routes/dolarRoutes'));
