const express = require("express");
const cors = require("cors");
const connectDB = require("./config/db");
const heladoRoutes = require('./routes/heladoRoutes');
require("dotenv").config();
const app = express();
connectDB();
app.use(cors());
app.use(express.json());
app.use("/api/helados", require("./routes/heladoRoutes"));
app.use("/api/empleados", require("./routes/empleadoRoutes"));
app.use("/api/dolar", require("./routes/dolarRoutes"));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));